CREATE TABLE TABLE_STUDENT (
        ID INT NOT NULL,
        FIRST_NAME VARCHAR(50) NOT NULL,
        LAST_NAME VARCHAR(20) NOT NULL,
        JOIN_DATE DATE,
        CREATE_DATE DATE,
        UPDATE_DATE DATE,
        COURSE VARCHAR (50) NOT NULL,
        PRIMARY KEY (ID)
);